site_name: GLAMpipe
nav:
  - Home: index.md
  - Getting started:
    - Installation: installation/index.md
  - Usage: 
    - Creating a project: workflow/create-project.md
    - Import data: workflow/import.md
  
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
