site_name: GLAMpipe
nav:
  - Home: index.md
  - Introduction: introduction/index.md
  - Getting started:
    - Installation: installation/index.md
    - Create your first project: quickstart/create-project.md
  - Usage:
    - Create project: workflow/create-project/index.md

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
